inherit_from: .rubocop_todo.yml

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'db/schema.rb'
    - 'app/admin/*.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
